export default {
    //Sync
    GET_LIST_OF_POSTS: "GET_LIST_OF_POSTS",
    RECIEVE_POST: "RECIEVE_POST",

    //Async
    GET_LIST_OF_POSTS_ASYNC: "GET_LIST_POSTS_ASYNC",
    RECIEVE_POST_ASYNC: "RECIEVE_POST_ASYNC",
    ADD_COMMENT_ASYNC: "ADD_COMMENT_ASYNC"
};
