export default {
    START_FETCHING: "START_FETCHING",
    STOP_FETCHING: "STOP_FETCHING",
    SHOW_ERROR_FETCHING: "SHOW_ERROR_FETCHING",
    HIDE_ERROR_FETCHING: "HIDE_ERROR_FETCHING",
    HIDE_SUCCES_LABEL: "HIDE_SUCCES_LABEL",
    SHOW_SUCCES_LABEL: "SHOW_SUCCES_LABEL"
};
